### PR TITLE
addon: bump go to 1.21

### PR DESCRIPTION
**Pull request by JoaoBraveCoding**

### CODE REVIEW

**Review by iblancasa — APPROVED** [review]
Thanks. I'm having a lot of problems because of Golang 1.20

**Review by douglascamata — CHANGES_REQUESTED** [review]
@JoaoBraveCoding considering we might have to build & distribute this through Red Hat's supported build systems for multiple reasons (compliance included), I think it's better that we stay with 1.20 for now.

**Comment by periklis** [comment]
Since March is coming soon we can start using 1.21 if this enables tracing making progress

**Comment by douglascamata** [comment]
That's an optimistic view, I would say. But fine for me if we want to take the risk. 👍

**Review by douglascamata — APPROVED** [review]

**Comment by JoaoBraveCoding** [comment]
I discussed with @iblancasa and we can stick with 1.20, it was my bad opening this one

**Pull request closed without merging**
